### PR TITLE
Mention nodejs-legacy in readme

### PR DESCRIPTION
**Pull request by jvoigtlaender**
Addresses https://github.com/kevva/elm-bin/issues/33 (and earlier https://github.com/kevva/elm-bin/issues/18).

### CODE REVIEW

**Comment by passy** [comment]
I'd rather link to a generic installation page for Node.js. This readme is not the right place for reiterating all installation caveats for all possible platforms.

**Comment by jvoigtlaender** [comment]
Makes sense. What would be an appropriate page (which, among other things, leads Debian/Ubuntu people to not only install Node.js itself, but also the nodjs-legacy package)?

**Comment by Zyndric** [comment]
> I'd rather link to a generic installation page for Node.js. This readme is not the right place for reiterating all installation caveats for all possible platforms.

You may be right. Still, some sort of help would be nice. This is a problem on all Debian/Ubuntu systems. The build's error message is no help at all. If this cannot be handled through dependency management, then the proposed simple message surely would not hurt the readme's brevity.

**Comment by passy** [comment]
I've asked around, and this seems to be the best resource when it comes to installation issues: https://github.com/npm/npm/wiki/Troubleshooting

**Comment by jvoigtlaender** [comment]
The troubleshooting page is nice, and I have added it to my pull request here. But I have also kept the note about `apt-get install nodejs-legacy`. My reasoning for this is:
* That specific problem and resolution for Debian/Ubuntu users is not mentioned on https://github.com/npm/npm/wiki/Troubleshooting
* We know that it is affecting people. At least twice this has already happened, #18 and #33, and it's not unlikely that it happens more frequently (who knows how many people have stumbled on this and found the solution themselves after some hassle).
* Why keep this solution "secret" when we have documented occurrences of the problem appearing which can be simply solved by it?

**Comment by passy** [comment]
Thanks, you've brought up a number of good points there. I think it's worth talking about this stuff before just adding bloat to the readme which in turn would lead to helping people *less*, but this is a solid trade-off.

**Comment by jvoigtlaender** [comment]
Thanks for merging!

**Pull request merged**
