### PR TITLE
Add static files needed for debug mode

### PR DESCRIPTION
**Pull request by jvoigtlaender**
This addresses the "debugger files not included" part of https://github.com/kevva/elm-bin/issues/7.

After `npm` installing a version of this package with those files now included, an `export ELM_HOME=.../node_modules/elm/share` should be enough to make the debug mode work okay.

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
Cool, thanks for merging this!

Can you release a new version of the package so we can try this out "live"? (I don't know that a "release" involves exactly. Is it just a matter of changing the version number in `package.json` and adding a GitHub tag? Or does it involve uploading some stuff to an `npm` database?)

**Comment by kevva** [comment]
Yup, basically. And running `npm publish`.

**Comment by kevva** [comment]
Should be published now.

**Comment by jvoigtlaender** [comment]
Hmm, seems not to be working. I suppose the reason is that you named the latest release "1.5.0" instead of "v1.5.0". The previous versions all had the form "v...", maybe some of the install code is depending on that "v"?

**Comment by kevva** [comment]
@jvoigtlaender, fixed now.

**Comment by jvoigtlaender** [comment]
Yes, works perfectly. Thanks!

**Pull request merged**
